export const SET_USER = 'SET_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const SET_USER_HISTORY = 'SET_USER_HISTORY'
export const ADD_WORKOUT = 'ADD_WORKOUT'
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY'
export const CLEAR = 'CLEAR'

export const CLEAR_WORKOUT = 'CLEAR_WORKOUT'
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const REPLACE_EXERCISE = 'REPLACE_EXERCISE'

export const SIGN_UP = "SIGN_UP";
export const LOGIN = "LOGIN"