export const SET_USER = 'SET_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const SET_USER_HISTORY = 'SET_USER_HISTORY'
export const SET_USER_FOLLOWING = 'SET_USER_FOLLOWING'
export const SET_USER_FOLLOWERS = 'SET_USER_FOLLOWERS'
export const ADD_WORKOUT = 'ADD_WORKOUT'
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY'
export const CLEAR = 'CLEAR'

export const SET_USERS = 'SET_USERS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const SET_USER_RUNS = 'SET_USER_RUNS'
export const ADD_RUN = 'ADD_RUN'

export const SET_USER_TEMPLATES = 'SET_USER_TEMPLATES'

export const SET_FEED = 'SET_FEED'
export const SET_UPCOMING = 'SET_UPCOMING'
export const SET_COMPLETED = 'SET_COMPLETED'

export const CLEAR_WORKOUT = 'CLEAR_WORKOUT'
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const REPLACE_EXERCISE = 'REPLACE_EXERCISE'

export const SIGN_UP = "SIGN_UP";
export const LOGIN = "LOGIN"

export const SET_USER_ACCRUED_ACHIEVEMENTS = 'SET_USER_ACCRUED_ACHIEVEMENTS'
export const ADD_ACCRUED_ACHIEVEMENT = 'ADD_ACCRUED_ACHIEVEMENT'
export const UPDATE_ACCRUED_ACHIEVEMENT = 'UPDATE_ACCRUED_ACHIEVEMENT'
export const SET_USER_SINGLE_ACHIEVEMENTS = 'SET_USER_SINGLE_ACHIEVEMENTS'
export const ADD_SINGLE_ACHIEVEMENT = 'ADD_SINGLE_ACHIEVEMENT'